name: Fix Codestyle

on:
  push:
    branches:
      - master

jobs:
  php-cs-fixer:
    name: Fix Code Style
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.0
        coverage: none
        tools: composer:v2

    - name: Install dependencies
      run: |
        composer update --prefer-dist --no-suggest --no-progress

    - run: composer php-cs-fixer src
      continue-on-error: true

    - run: git checkout -- composer.json

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: php-cs-fixer
        commit_author: azure-client-credentials <azure-oauth2-validator@users.noreply.github.com>
